[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*", "https://storage.googleapis.com/.*", "https://cloudinary.com/.*", "https://cdn.example.com/.*", "https://res.cloudinary.com/.*", "https://i.imgur.com/.*", "https://fastly.jsdelivr.net/.*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"